datasource:
  type: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: ry-vue
  autoLoadEntities: true
  synchronize: false
  charset: utf8mb4
  timezone: '+08:00'
  # 连接池配置
  pool:
    connectionLimit: 20      # 最大连接数
    waitForConnections: true
    queueLimit: 0
    connectTimeout: 30000